[server]
maxUploadSize = 1000
enableXsrfProtection = false
enableCORS = false

[theme]
base = "dark"
primaryColor = "#00ADB5"
backgroundColor = "#0b132b"
secondaryBackgroundColor = "#1c2541"
textColor = "#FFFFFF"
font = "sans serif"
